name: Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: npm install
    - name: Build and Publish
      env:
        HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: todo-api-pipeline
      if: github.ref == 'refs/heads/master' && job.status == 'success'
      run: |
        git remote add heroku https://heroku:$HEROKU_API_TOKEN@git.heroku.com/todo-api-pipeline.git
        git push heroku HEAD:refs/heads/master -f
  
  api-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Newman
        run: npm install -g newman newman-reporter-htmlextra
      - name: Test and Generate Report
        run: |
          newman run todo-api.postman_collection --environment Production.postman_environment.json --reporters cli,htmlextra --reporter-htmlextra-export "newman/report.html"
          ls -a
      - name: Archive api test results
        uses: actions/upload-artifact@v2.2.4
        with:
          name: api-test-report
          path: newman/report.html
